name: Vulcan
version: 1.0
api-version: 1.16
main: me.zeph.vulcan.vulcan.Vulcan
depend: [ProjectKorra]
authors: [Zeph]
description: Improves lavabending
loadbefore: [PKConfigApi]
vulcan.player:
    default: true
    description: Access to vulcan abilities.
    children:
      bending.ability.Erupt: true
      bending.ability.IgneousShift: true
      bending.ability.LavaLine: true
      bending.ability.LavaStream: true
      bending.ability.LavaTendril: true
      bending.ability.MagmaMelt: true
